language: c

compiler:
    - gcc

git:
  depth: 1

install:
    - sudo apt-get update -qq
    - sudo pip install cpp-coveralls
    - sudo pip install requests==2.5.3
    - sudo apt-get install -qq cmake python3-minimal
    - sudo apt-get install -qq valgrind
    - sudo apt-get install -qq libcunit1-dev

script:
    - ./clean.py --rebuild
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make
    - make run

after_success:
    - coveralls --include ./build


